### ISSUE TITLE
can't connect to peers

### ISSUE THREAD

**Issue by HeBeHo** [etica/etica-gui#2]
My GUI wallet (Win11) stucks from the beginning to connect to peers. It shows on the bottom line "connecting to peers, please wait..." for hours / days. Sometimes in the left bottom corner I can see "peer count" 2 or 4 or something for a few seconds and then again zero. It has never been connected or synchronized. Any trick to bring it to connect?

**Comment by kevin-wad** [comment]
Hi, sorry for late answer I just saw your comment. This issue happens when you download the windows build but you have never installed wallet from source. I will fix it in coming days. In the meanwhile please try to first install wallet from source, it should resolve this issue

**Comment by kevin-wad** [comment]
Issue resolved. This release fixes this issue:
https://github.com/etica/etica-gui/releases/tag/v1.0.4

**Comment by kevin-wad** [comment]
> My GUI wallet (Win11) stucks from the beginning to connect to peers. It shows on the bottom line "connecting to peers, please wait..." for hours / days. Sometimes in the left bottom corner I can see "peer count" 2 or 4 or something for a few seconds and then again zero. It has never been connected or synchronized. Any trick to bring it to connect?

 @HeBeHo Issue is now resolved. Check latest release: https://github.com/etica/etica-gui/releases/tag/v1.0.4
Thanks for patience
